// 我真诚地保证：
// 我自己独立地完成了整个程序从分析、设计到编码的所有工作。
// 如果在上述过程中，我遇到了什么困难而求教于人，那么，我将在程序实习报告中
// 详细地列举我所遇到的问题，以及别人给我的提示。
// 我的程序里中凡是引用到其他程序或文档之处，
// 例如教材、课堂笔记、网上的源代码以及其他参考书上的代码段,
// 我都已经在程序的注释里很清楚地注明了引用的出处。
// 我从未抄袭过别人的程序，也没有盗用别人的程序。
// 安俊豪
// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ================================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// UsersDao is the data access object for table users.
type UsersDao struct {
	table   string
	columns usersColumns
	group   string
	db      gdb.DB
}

// usersColumns defines and stores column names for table users.
type usersColumns struct {
	Id        string
	Name      string
	Email     string
	Phone     string
	Password  string
	Status    string
	CreatedAt string
	UpdatedAt string
}

var usersColumnsInfo = usersColumns{
	Id:        "id",
	Name:      "name",
	Email:     "email",
	Phone:     "phone",
	Password:  "password",
	Status:    "status",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

func NewUsersDao() *UsersDao {
	return &UsersDao{
		group:   "default",
		table:   "users",
		columns: usersColumnsInfo,
	}
}

func (dao *UsersDao) DB() gdb.DB {
	if dao.db != nil {
		return dao.db
	}
	dao.db = g.DB(dao.group)
	return dao.db
}

func (dao *UsersDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

func (dao *UsersDao) Table() string {
	return dao.table
}

func (dao *UsersDao) Columns() usersColumns {
	return dao.columns
}

func (dao *UsersDao) Group() string {
	return dao.group
}
