// 我真诚地保证：
// 我自己独立地完成了整个程序从分析、设计到编码的所有工作。
// 如果在上述过程中，我遇到了什么困难而求教于人，那么，我将在程序实习报告中
// 详细地列举我所遇到的问题，以及别人给我的提示。
// 我的程序里中凡是引用到其他程序或文档之处，
// 例如教材、课堂笔记、网上的源代码以及其他参考书上的代码段,
// 我都已经在程序的注释里很清楚地注明了引用的出处。
// 我从未抄袭过别人的程序，也没有盗用别人的程序。
// 安俊豪
// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Books is the golang structure for table books.
type Books struct {
	Id          uint64      `json:"id"           description:"图书ID"`
	Title       string      `json:"title"        description:"图书名称"`
	Author      string      `json:"author"       description:"作者"`
	Isbn        string      `json:"isbn"         description:"ISBN号"`
	PublishDate *gtime.Time `json:"publish_date" description:"出版日期"`
	Status      int8        `json:"status"       description:"状态：1-可借阅，0-已借出，2-下架"`
	CreatedAt   *gtime.Time `json:"created_at"   description:"创建时间"`
	UpdatedAt   *gtime.Time `json:"updated_at"   description:"更新时间"`
}
