// 我真诚地保证：
// 我自己独立地完成了整个程序从分析、设计到编码的所有工作。
// 如果在上述过程中，我遇到了什么困难而求教于人，那么，我将在程序实习报告中
// 详细地列举我所遇到的问题，以及别人给我的提示。
// 我的程序里中凡是引用到其他程序或文档之处，
// 例如教材、课堂笔记、网上的源代码以及其他参考书上的代码段,
// 我都已经在程序的注释里很清楚地注明了引用的出处。
// 我从未抄袭过别人的程序，也没有盗用别人的程序。
// 安俊豪
// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Borrows is the golang structure for table borrows.
type Borrows struct {
	Id        uint64      `json:"id"         description:"借阅记录ID"`
	UserId    uint64      `json:"user_id"    description:"用户ID"`
	BookId    uint64      `json:"book_id"    description:"图书ID"`
	BorrowAt  *gtime.Time `json:"borrow_at"  description:"借阅时间"`
	ReturnAt  *gtime.Time `json:"return_at"  description:"归还时间"`
	CreatedAt *gtime.Time `json:"created_at" description:"创建时间"`
	UpdatedAt *gtime.Time `json:"updated_at" description:"更新时间"`
}
